### ISSUE TITLE
images no longer available 

### ISSUE THREAD

**Issue by derekdickerson** [igorpecovnik/Cubox-i-Debian#5]
Figures images have been taken down.

**Comment by igorpecovnik** [comment]
yes. It will be solved asap.

**Comment by derekdickerson** [comment]
I noticed the download is in a bad location can you put the files on mega.co.nz?
http://d-h.st/HOwL<--this seems scary but not sure if mega.co.nz costs money.

also not trying to spam you but check out my linux devboard group here
https://www.facebook.com/groups/361823037310180/
Thanks for all your work btw
@igorpecovnik
